### PR TITLE
Golang automatic install without download(with version find Automatically)

### PR DESCRIPTION
**Pull request by goody80**
Please check this code out :)

Thanks.

### CODE REVIEW

**Comment by canha** [comment]
Sorry for not looking at this sooner but I've been busy. I took a peek but I have some concerns for which I'll need to make some comments on.

**Comment by goody80** [comment]
This ticket has been closed and move to new ticket as below
 - https://github.com/canha/golang-tools-install-script/pull/16

**Comment by goody80** [comment]
This ticket has been closed and move to new ticket as below
 - https://github.com/canha/golang-tools-install-script/pull/16

**Comment by goody80** [comment]
This ticket has been closed and move to new ticket as below
 - https://github.com/canha/golang-tools-install-script/pull/16

**Comment by goody80** [comment]
This ticket has been closed and move to new ticket as below
 - https://github.com/canha/golang-tools-install-script/pull/16

**Comment by goody80** [comment]
Create a new ticket for conflict clean as below
 - https://github.com/canha/golang-tools-install-script/pull/17

**Comment by goody80** [comment]
Create a new ticket for conflict clean as below
 - https://github.com/canha/golang-tools-install-script/pull/17

**Pull request closed without merging**
