### PR TITLE
update to main.sh

### PR DESCRIPTION
**Pull request by mxplusb**
I just refactored a couple things. Just pass the go version as the first argument.
Example installation: `bash main.sh 1.5.1`
Example removal: `bash main.sh 1.5.1 --remove`

This allows for multiple versions and stuff.

### CODE REVIEW

**Comment by canha** [comment]
Hi! Thanks for contributing.

What happens when you install a different version over an already installed one? Won't the old one just keep being used due to the path's position taking precedence? I understand you might want to install different versions but either keep the folder name the same or find a solution to the path so that you can easily override with new versions. What do you think?

**Comment by mynameismevin** [comment]
If you are using multiple versions of Go, you can't have multiple global `GOPATH` environment variables. Personally, I would just write a `go1.x` bash function like this:

```bash
function go14 () {
    echo -e " \
export GOROOT=$HOME/.go14 \
export PATH=$PATH:$GOROOT/bin \
export GOPATH=$HOME/go14 \
export PATH=$PATH:$GOPATH/bin"
go $@
unset {...}
}
```

Then instead of calling `go version`, you call `go14 version`. Also, your script didn't work on my Ubuntu 15.04 box because it didn't set the variables in `.bash_profile`. It might just be better to send the environmental variables to stdout and let the user decide what to do with them. Just my opinion though.

**Comment by canha** [comment]
Yes, I'll try to think of some simple solution when possible. I'll leave this open until then.

**Comment by mynameismevin** [comment]
Sounds good! Thanks for letting me help improve it. :+1:

**Comment by samrocketman** [comment]
# GO enVironment Manager proposal

You could take a leaf out of `rvm`'s book with the `use` function.  `gvm` (for groovy) has a similar function but implemented a little differently.  You could just create a built-in `govm` function (GO enVironment Manager) that a user can source in their `.bashrc`/`.bash_profile`.  It could operate akin to the following settings.

## ~/.govm for all settings
e.g. Let's say there's a config directory located at `~/.govm` and in that directory there's `init.sh` akin to `main.sh`.

### init.sh sourced by user profiles

Add the following line to `~/.bashrc` or `~/.bash_profile` depending if your bash is recognized as a login prompt or not.

```bash
[ -e "${HOME}/.govm/init.sh" ] && source "${HOME}/.govm/init.sh"
```

When you source `init.sh` it creates a shell function `govm` which has multiple subcommands (`install`, `uninstall`, and `use` a three off the top of my head).

## govm install

```bash
govm install 1.5.1
```

Will install go under `~/.govm/root/go1.5.1`.  It will also set up a default `GOPATH` under `~/.govm/path/go1.5.1/default` and `~/.govm/path/go1.5.1/global`.

## govm use

```bash
govm use 1.5.1
govm use 1.5.1@mypath
```

#### govm use 1.5.1

If the `@` symbol is omitted then it is assumed the user wanted `govm use 1.5.1@default`.

This will automatically set the following environment variables.

```bash
export GOROOT="${HOME}/.govm/root/go1.5.1"
export GOPATH="${HOME}/.govm/path/go1.5.1/global:${HOME}/.govm/path/go1.5.1/default"
```

#### govm use 1.5.1@mypath

Since the user specified `@mypath` it's assumed the user wanted a custom GOPATH.  Therefore, the following environment variables will be set.

```bash
export GOROOT="${HOME}/.govm/root/go1.5.1"
export GOPATH="${HOME}/.govm/path/go1.5.1/global:${HOME}/.govm/path/go1.5.1/mypath"
```

If `${HOME}/.govm/path/go1.5.1/mypath` doesn't exists then it will be created.

## Conclusions

This is mostly just guessing on my part because I know next to nothing about `go` nor how it handles dependencies.  This proposal mostly comes from a few quick google searches and this pull request conversation.

**Comment by canha** [comment]
Hey @samrocketman. I'm currently working on improving this script. However, I already know of gvm here on GitHub, which basically does what you just described. I'm wondering if I should keep working on this - if it's even useful for people.

**Comment by samrocketman** [comment]
@canha I'm not sure I can answer whether people find it useful.  The question is do _you_ find it useful?  I typically write utilities for myself and if they're useful for other people then more power to 'em.

I was proposing `govm` because I thought it would be a nice trade-off between a lightweight shell script and managing more than one go version (root path and go path).  I don't currently program in Go but I could see something like this useful if I did (given my limited understanding of GOROOT and GOPATH).

**Comment by canha** [comment]
@samrocketman I agree. This was since the beginning a personal fast way to get Go installed on my machines. I'm certainly reflecting on it. I don't think it makes sense to do work that has been already done by the community, so I might just keep it simple. I'll give myself some time to think about it. Thanks thanks giving your feedback as well. :+1:

**Pull request closed without merging**
