### PR TITLE
Check environment variables GOROOT and GOPATH before installation

### PR DESCRIPTION
**Pull request by vhaidamaka**
Please, review it.
Thank you.

### CODE REVIEW

**Comment by kerolloz** [comment]
@vhaidamaka 
please check my [repo](/kerolloz/go-installer)

**Comment by canha** [comment]
Sorry it took me long to get to this. I've resolved the conflicts and I like the idea of being able to override these. Thanks!

**Comment by vhaidamaka** [comment]
@canha, thanks for merging PR.
But it seems that during conflict resolution you have missed a few changes, that will not reflect $GOROOT environment variable during installation - golang will be installed into the $HOME/.go dir everytime, but GOROOT in shell profile will be written from the environment variable.
Take a look, please, at diff against latest master:
```
$ git diff
diff --git a/goinstall.sh b/goinstall.sh
index 38d800e..30ff3aa 100755
--- a/goinstall.sh
+++ b/goinstall.sh
@@ -71,8 +71,8 @@ elif [ ! -z "$1" ]; then
     exit 1
 fi

-if [ -d "$HOME/.go" ]; then
-    echo "The '.go' directory already exists. Exiting."
+if [ -d "$GOROOT" ]; then
+    echo "$GOROOT directory already exists. Exiting."
     exit 1
 fi

@@ -89,9 +89,8 @@ if [ $? -ne 0 ]; then
 fi

 echo "Extracting File..."
-mkdir -p "$HOME/.go/"
-tar -C "$HOME/.go" --strip-components=1 -xzf /tmp/go.tar.gz
-touch "$HOME/.${shell_profile}"
+mkdir -p "$GOROOT"
+tar -C "$GOROOT" --strip-components=1 -xzf /tmp/go.tar.gz
 {
     echo '# GoLang'
     echo "export GOROOT=${GOROOT}"
@@ -101,7 +100,7 @@ touch "$HOME/.${shell_profile}"
 } >> "$HOME/.${shell_profile}"

 mkdir -p $GOPATH/{src,pkg,bin}
-echo -e "\nGo $VERSION was installed.\nMake sure to relogin into your shell or run:"
+echo -e "\nGo $VERSION was installed into $GOROOT.\nMake sure to relogin into your shell or run:"
 echo -e "\n\tsource $HOME/.${shell_profile}\n\nto update your environment variables."
 echo "Tip: Opening a new terminal window usually just works. :)"
 rm -f /tmp/go.tar.gz
```
Add please these changes.

**Comment by canha** [comment]
You are totally right, adding those! Thanks again.

**Pull request merged**
